openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:

components:
  schemas:
    contact:
      properties:
        address_list:
          type: array
          items:
            type: integer

  
