# generated by datamodel-codegen:
#   filename:  input/anvil.yaml
#   timestamp: 2021-12-15T12:25:53+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class Users(BaseModel):
    email: Optional[str] = None
    enabled: Optional[bool] = None
    signed_up: Optional[datetime] = None
    password_hash: Optional[str] = None
    confirmed_email: Optional[bool] = None
    email_confirmation_key: Optional[str] = None
    n_password_failures: Optional[int] = None
    last_login: Optional[datetime] = None
    remembered_logins: Optional[Dict[str, Any]] = None


class Email(BaseModel):
    address: Optional[str] = None
    created_by: Optional[Users] = None
    created_on: Optional[datetime] = None
    place: Optional[int] = None


class Phone(BaseModel):
    number: Optional[str] = None
    created_by: Optional[Users] = None
    created_on: Optional[datetime] = None


class Contact(BaseModel):
    name: Optional[str] = None
    phone: Optional[Phone] = None
    email_list: Optional[List[Email]] = None
    age: Optional[float] = None
    created_by: Optional[Users] = None
    created_on: Optional[datetime] = None
    family: Optional[List[int]] = None
    uid: Optional[int] = None
    father: Optional[Contact] = None


Contact.update_forward_refs()
